//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAdmin.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDBEntities : DbContext
    {
        public SchoolDBEntities()
            : base("name=SchoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGallery> tblGalleries { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Subject_Combination> Subject_Combination { get; set; }
        public virtual DbSet<Subject_Master> Subject_Master { get; set; }
        public virtual DbSet<Application_Master> Application_Master { get; set; }
        public virtual DbSet<Student_Master> Student_Master { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Stream_Master> Stream_Master { get; set; }
    }
}
