//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stream_Master
    {
        public int Stream_ID { get; set; }
        public string StreamName { get; set; }
        public bool IsActive { get; set; }
    }
}
