//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Combination
    {
        public int Combination_ID { get; set; }
        public int FirstChoice { get; set; }
        public int SecondChoice { get; set; }
        public int StreamID { get; set; }
    }
}
