//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myAdmin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGallery
    {
        public int imgID { get; set; }
        public string ImageTitle { get; set; }
        public string ImageDesc { get; set; }
    }
}
